version: '3.1'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - postgres
    env_file:
      - ./containers/grafana/config.monitoring
    volumes:
      - ./containers/grafana/dashboard:/etc/extra-config/grafana
    command: ./etc/extra-config/grafana/post.sh
  
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - ./containers/postgres/postgres.env
    ports:
      - 5432:5432                
    volumes:
      - ./containers/postgres/sql:/docker-entrypoint-initdb.d

  jupyterlab:
    container_name: jupyterlab
    build:
      context: ./containers/notebook
    env_file:
      - ./containers/notebook/notebook.env
    ports:
        - 8888:8888
    volumes:
        - ./containers/notebook/projects:/notebook
