{
 "title": "Flight Monitor",
 "description": "Observing Airlines in Box [56.75,55.20,4.59,17.27]",
 "tags": [ "flights" ],
 "time": { "from": "now-5s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "No. of Flights seen Last 15 minutes",
   "type": "stat",
   "description": "Monitoring Bound: [56.75,55.20,4.59,17.27]",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airline_data",
     "query": "SELECT count( distinct \"uuid\") as c FROM \"autogen\".\"airlines\" WHERE $timeFilter GROUP BY c",
     "select": [
      [
       { "params": [ "airline" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Radar",
   "type": "grafana-worldmap-panel",
   "description": "//  \"airline\",  \"flight_number\", \"flight_tag\", \"from\",  \"to\", \"track_degree\", \"uuid\" ,  \"icao_id\", ",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airline_data",
     "query": "SELECT \"icao_id\", \"ground_speed_kts\", \"latitude\", \"longitude\" FROM \"autogen\".\"airlines\"  WHERE $timeFilter\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Flights",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Flights",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airlines",
     "query": "SELECT count(distinct(\"uuid\")) FROM \"autogen\".\"airlines\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uuid" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}